openapi: 3.0.0
servers:
  - url: 'https://devquotesapi.flightcommand.com/quoting/v1'
  - url: 'http://localhost:3000/v1'
info:
  version: 1.0.0
  title: Quoting API
  description: Flight command quoting API
security:
  - Authorization: []
paths:
  /airports/closest:
    get:
      summary: Get closest airports from location
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: miles
          in: query
          schema:
            type: string
          description: Search mile radius
        - name: lat
          in: query
          description: Origin latitude
          schema:
            type: string
        - name: lng
          in: query
          description: Origin longitude
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  - code: AUS
                    ICAO: KAUS
                    IATA: AUS
                    faaCode: AUS
                    city: Austin
                    state: Texas
                    lat: 30.19499969482422
                    lng: -97.66999816894531
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  /airports/flightTime:
    get:
      summary: Calculate flight time to airport. Returns the time in second
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: oicao
          in: query
          description: Origin ICAO
          schema:
            type: string
        - name: dicao
          in: query
          description: desitination ICAO
          schema:
            type: string
        - name: speed
          in: query
          description: Aircraft moving speed in miles per hour
          schema:
            type: string
            default: 500
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  flightTime: 3443
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  /tails:
    get:
      summary: Fetch aircrafts
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: limit
          in: query
          schema:
            type: number
            default: 50
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  - id: 130003
                    number: NEP01XZ
                    model: Super-Mid
                    serialNumber: 880
                    callSign: SPT
                    seats: 10
                    defaultSpeed: 568970
                    rate: 1000
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  /trips/prepareTrip:
    post:
      description: ok
      requestBody:
        content:
          application/json:
            schema:
              example:
                passengers: 3
                legs:
                  - origin:
                      airport:
                        ICAO: KMHC
                        lat: 2.222
                        lng: 3.3333
                    destination:
                      airport:
                        ICAO: KMHC
                        lat: 4.222
                        lng: 5.3333
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  totalFlightTime: 163
                  totalLiveTime: 115
                  totalRepoTime: 48
                  legs:
                    - origin:
                        ICAO: KBOS
                        lat: 2.222
                        lng: 3.3333
                      destination:
                        ICAO: KBOS
                        lat: 2.222
                        lng: 3.3333
                  operators:
                    - tailId: 124255
                      tailNumber: N179MT
                      efficiency: 89
                      vendorId: 1
                      vendorName: Tail but No Operator Info
                      homeBase: KMHT
                      liveRate: 25000
                      model: ANALAR CO
                      category: null
                      defaultSpeed: 500
                      amenities:
                        wifi: true
                        lavatory: false
                        pets: false
                        heating: false
                        ownerApproval: true
                      seats: 5
                      repoLegs:
                        - origin: KMHT
                          destination: KOWD
                          type: repo
                          flightTime: 49
                      totalFlightTime: 117
                      totalPrice: 1000
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  /rfqs/summary:
    get:
      summary: Fetch RFQs stats
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  outbound:
                    todayQuotesCount: 6
                    confirmedQuoteCount: 2
                    pendingQuoteCount: 2
                  inbound:
                    todayQuotesCount: 6
                    confirmedQuoteCount: 2
                    pendingQuoteCount: 2
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  /rfqs:
    post:
      summary: Create an RFQ
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      requestBody:
        content:
          application/json:
            schema:
              example:
                flightTime: 16300
                departureDate: '2019-01-08T18:20:43.415Z'
                passengersCount: 2
                legs:
                  - origin:
                      airport:
                        ICAO: KOWD
                    destination:
                      airport:
                        ICAO: KPVD
                    type: live
                    flightTime: 4600
                vendors:
                  - id: 1
                    tailId: 124255
                    tailNumber: N179MT
                    flightTime: 22333
                    totalPrice: 22220
                    rate: 2000
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  id: 925820597
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  /rfqs/sent:
    get:
      summary: Fetch all user RFQs sent
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  - id: 465058874sdbbsdhs
                    number: 92929
                    lowPrice: 1000000
                    highPrice: 2000000
                    quotesCount: 3
                    route: BOS-MCO-MIA
                    createdAt: '2018-12-19T15:46:48.860Z'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  /rfqs/received:
    get:
      summary: Fetch all received RFQs
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  - id: 465058874
                    number: 89438439
                    tail:
                      number: N526MP
                      model: Super-Mid
                    route: BOS-MCO-MIA
                    vendorName: OneSky
                    buyerName: ACI
                    flightTime: 3600
                    rate: 25000
                    fees: 25000
                    totalPrice: 25000
                    createdAt: '2018-12-19T15:46:48.860Z'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  '/rfqs/{rfqId}':
    get:
      summary: Fetch specific RFQ
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - in: path
          name: rfqId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  id: 465058874
                  route: BOS-MCO-MIA
                  departDate: '2018-12-19T15:46:48.860Z'
                  passengersCount: 2
                  flightTime: 3000
                  confirmed: false
                  createdAt: '2018-12-19T15:46:48.860Z'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
    put:
      summary: Fetch specific RFQ
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - in: path
          name: rfqId
          required: true
          schema:
            type: string
        - in: query
          name: viewed
          schema:
            type: boolean
        - in: query
          name: canceled
          schema:
            type: boolean
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  id: 465058874
                  route: BOS-MCO-MIA
                  departDate: '2018-12-19T15:46:48.860Z'
                  passengersCount: 2
                  flightTime: 3000
                  confirmed: false
                  createdAt: '2018-12-19T15:46:48.860Z'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  '/rfqs/{rfqId}/quotes':
    get:
      summary: Fetch RQF quotes
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: rfqId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  - id: 9034039403943904000
                    docuSignEnvelopeId: 5c2e71b95c4f6197c1b1f349
                    sellerName: Joe Brown
                    vendor:
                      id: 945454
                      name: Flight Hight
                    tail:
                      number: N526MP
                      model: Super-Mid
                    flightTime: 3600
                    rate: 250000
                    fees: 100000
                    totalPrice: 1000000
                    terms:
                      agreement: some text
                      cancellation: Before 24h
                      refund: Not refundable
                    completed: false
                    viewed: false
                    createdAt: '2018-12-19T15:46:48.860Z'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
    post:
      summary: Create quotes for RFQ
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: rfqId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              example:
                tailNumber: NF300PQ
                flightTime: 34343
                rate: 3000000
                parkingFees: '0,'
                fuelFees: '0,'
                landingFees: '0,'
                overnightFees: 10000
                totalFees: 10000
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  id: 8594854994849545
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  '/quotes/{quoteId}':
    get:
      summary: Fetch quote detail
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - in: path
          name: quoteId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  id: 38498493843934
                  rfqId: 9438394893
                  operator:
                    id: 94545433
                    name: Flight Hight
                  tailNumber: NF300PQ
                  time: 3600
                  rate: 250000
                  fees: 100000
                  price: 1000000
                  terms:
                    agreement: some text
                    cancellation: Before 24h
                    refund: Not refundable
                  seenAt: '2018-12-19T15:46:48.860Z'
                  createdAt: '2018-12-19T15:46:48.860Z'
                  completed: false
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  '/quotes/{quoteId}/confirmation':
    post:
      summary: Confirm a quote
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - name: quoteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  rfqId: 465058874
                  envelopeId: c01e682d-401d-449c-86d3-a61b6b355a90
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  '/quotes/envelopes/{envelopeId}/signing':
    post:
      summary: Fetch user confirmation signing document link
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - in: path
          name: envelopeId
          required: true
          schema:
            type: string
        - in: query
          name: event
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example: null
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
  '/quotes/envelopes/{envelopeId}/embeddedLink':
    post:
      summary: Fetch user confirmation signing document link
      parameters:
        - in: header
          name: Authentication
          required: true
          schema:
            type: string
            example: >
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        - in: path
          name: envelopeId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                returnUrl: 'http://domain.com/callback'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                example:
                  uri: >-
                    https://demo.docusign.net/Signing/startinsession.aspx?t=fd6b9e60-e6f6-4260-a9fc-1f4d2e1973d1&pei=d1cf4bea-1b78-47ea-b372-746678e3679f
                  expiredIn: 9043
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 400
                    message: The request was unacceptable
                    errors: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 401
                    message: >-
                      The request has not been applied because it lacks valid
                      authentication credentials for the target resource.
                    errors: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 403
                    message: >-
                      The server understood the request, but is refusing to
                      fulfill it
                    errors: []
        '500':
          description: A technical error occured in Restlet Cloud
          content:
            application/json:
              schema:
                example:
                  error:
                    code: 500
                    message: >
                      The server understands the content type of the request
                      entity, and the syntax of the request entity is correct,
                      but was unable to process the contained instructions.
                    errors: []
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT

